# Generated by Django 4.2.24 on 2025-09-05 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booktest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hname", models.CharField(max_length=20)),
                ("hgender", models.BooleanField()),
                ("hcomment", models.CharField(max_length=100)),
                (
                    "hbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booktest.bookinfo",
                    ),
                ),
            ],
        ),
    ]
